version: '3.2'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: zaiminc/gocat:dev
    ports:
      - 3000:3000
    volumes:
      - .:/bot
      - ~/.kube/config:/root/.kube/config
    environment:
      LOCAL: "true"
      CONFIG_MANIFEST_REPOSITORY:
      CONFIG_GITHUB_ACCESS_TOKEN:
      CONFIG_GITHUB_DEFAULT_BRANCH:
      CONFIG_SLACK_VERIFICATION_TOKEN:
      CONFIG_SLACK_OAUTH_TOKEN:
      CONFIG_JENKINS_HOST:
      CONFIG_JENKINS_BOT_TOKEN:
      CONFIG_JENKINS_JOB_TOKEN:
      CONFIG_ARGOCD_HOST:
      CONFIG_NAMESPACE:
      CONFIG_ENABLE_AUTO_DEPLOY: "false"
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
